Repository TeamOctolings/Octobot, pull requests merged in 2022-12, with the labels that each got.

#7 Unhardcoded bot mention + some small fixes
  .gitignore
  Boyfriend/Boyfriend.cs
  Boyfriend/CommandProcessor.cs
  Boyfriend/Messages.tt-ru.resx
Labels: type: enhancement

#8 Keep reply emojis as consts in a separate class
  Boyfriend/CommandProcessor.cs
  Boyfriend/Commands/BanCommand.cs
  Boyfriend/Commands/HelpCommand.cs
  Boyfriend/Commands/KickCommand.cs
  Boyfriend/Commands/MuteCommand.cs
  Boyfriend/Commands/PingCommand.cs
  Boyfriend/Commands/SettingsCommand.cs
  Boyfriend/Commands/UnmuteCommand.cs
  Boyfriend/ReplyEmojis.cs
Labels: type: security & quality

#9 List supported languages if an invalid one is provided
  Boyfriend/Boyfriend.cs
  Boyfriend/Commands/SettingsCommand.cs
  Boyfriend/EventHandler.cs
  Boyfriend/Messages.Designer.cs
  Boyfriend/Messages.resx
  Boyfriend/Messages.ru.resx
  Boyfriend/Messages.tt-ru.resx
  Boyfriend/ReplyEmojis.cs
Labels: type: bugfix, type: enhancement

#10 Add ReSharper code inspection
  .github/workflows/codeql.yml
  .github/workflows/resharper.yml
  Boyfriend/Boyfriend.cs
  Boyfriend/CommandProcessor.cs
  Boyfriend/EventHandler.cs
Labels: type: security & quality
