Repository TeamOctolings/Octobot, pull requests merged in 2023-11, with the labels that each got.

#178 Use IFeedbackService interface instead of implementation
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Extensions/FeedbackServiceExtensions.cs
Labels: size/S, type: change

#177 Check interactions in MemberUpdateService before operating on members
  src/Responders/GuildLoadedResponder.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: fix, size/M

#179 Add more information to guild loaded log message
  src/Responders/GuildLoadedResponder.cs
Labels: size/XS, type: change

#194 Make issue templates less annoying
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: area: docs, size/S, type: change

#196 Put edited message in cache if it's not in cache already
  src/Responders/MessageEditedResponder.cs
Labels: type: fix, size/XS

#195 Combine Dependabot PRs updating Remora.Discord packages into one
  .github/dependabot.yml
Labels: size/XS, area: build/ci, type: change

#192 Update CDN links for Octobot banner
  docs/README.md
  src/Commands/AboutCommandGroup.cs
Labels: area: docs, size/XS
