Repository TeamOctolings/Octobot, pull requests merged in 2023-10, with the labels that each got.

#137 Remove all non-Splatoon songs
  src/Services/Update/SongUpdateService.cs
Labels: size/XS, type: song list

#136 Make README slightly better
  docs/README.md
Labels: type: docs, size/XS

#135 Add MORE Splatoon™ songs that I liked
  src/Services/Update/SongUpdateService.cs
Labels: size/XS, type: song list

#139 Add string interpolation for SongUpdateService
  src/Services/Update/SongUpdateService.cs
Labels: size/S, area: song list, type: change

#141 fix(i18n): [RU] do not use colloquialisms in ReminderText
  locale/Messages.ru.resx
Labels: type: fix, size/XS, area: i18n

#140 Add /timestamp
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/ToolsCommandGroup.cs
  src/Messages.Designer.cs
Labels: type: feature, size/S

#144 Remove unused messages
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Messages.Designer.cs
Labels: type: fix, size/L, area: i18n

#143 Fix /unmute not checking if the target is muted
  src/Commands/MuteCommandGroup.cs
Labels: type: fix, size/S

#138 Update /random
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/ToolsCommandGroup.cs
  src/Messages.Designer.cs
Labels: type: fix, size/M, type: change

#146 Unload guild datas when they become unavailable
  src/Responders/GuildUnloadedResponder.cs
  src/Services/GuildDataService.cs
Labels: type: fix, size/S

#147 Edit log output in GuildLoadedResponder
  src/Responders/GuildLoadedResponder.cs
Labels: size/XS, type: change

#145 Use one common method in /mute
  src/Commands/MuteCommandGroup.cs
Labels: size/M, type: refactor/style

#150 Update .gitignore
  .gitignore
Labels: size/XS

#151 Correct illegal nickname characters regex
  src/Services/Update/MemberUpdateService.cs
Labels: type: fix, size/XS

#153 Rename /showinfo to avoid confusion with /guildinfo
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/ToolsCommandGroup.cs
  src/Messages.Designer.cs
Labels: size/M, type: change

#156 Change reminders sorting in /listremind
  src/Commands/RemindCommandGroup.cs
Labels: size/XS, type: change

#155 /remind: Switch away from zero-based numbering and rename `index`
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/RemindCommandGroup.cs
  src/Messages.Designer.cs
Labels: size/S, type: change

#157 Rename Reminder message to Reminder text
  src/Commands/RemindCommandGroup.cs
Labels: size/XS, type: change

#158 Use link button for created event message
  src/InteractionResponders.cs
  src/Octobot.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: size/S, type: change

#159 Sanitize scheduled event names
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: size/XS, type: change

#160 Correct issue label names per recent changes
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/dependabot.yml
Labels: type: fix, size/XS

#161 Split extension methods into separate classes
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/Events/LoggingPreparationErrorEvent.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Data/Options/SnowflakeOption.cs
  src/Extensions.cs
  src/Extensions/CollectionExtensions.cs
  src/Extensions/CommandContextExtensions.cs
  src/Extensions/DiffPaneModelExtensions.cs
  src/Extensions/EmbedBuilderExtensions.cs
  src/Extensions/FeedbackServiceExtensions.cs
  src/Extensions/GuildScheduledEventExtensions.cs
  src/Extensions/LoggerExtensions.cs
  src/Extensions/SnowflakeExtensions.cs
  src/Extensions/StringExtensions.cs
  src/Extensions/UInt64Extensions.cs
  src/Extensions/UserExtensions.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Responders/MessageDeletedResponder.cs
  src/Responders/MessageEditedResponder.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Update/ScheduledEventUpdateService.cs
  src/Services/UtilityService.cs
Labels: size/L, type: refactor/style

#162 Sanitize input text in message edit log
  src/Extensions/DiffPaneModelExtensions.cs
  src/Extensions/StringExtensions.cs
Labels: type: fix, size/S

#166 Fix Reminder serialization/deserialization
  src/Data/MemberData.cs
  src/Data/Reminder.cs
Labels: type: fix, size/XS

#165 Use MemberData to determine a subscriber's role list
  src/Services/Update/ScheduledEventUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: fix, size/XS

#169 Add filtering by message author to /clear
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/ClearCommandGroup.cs
  src/Messages.Designer.cs
Labels: type: feature, size/S

#167 Do not try to send messages in empty EventNotificationChannels
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: fix, size/S

#168 Unschedule scheduled event status update only if last update was successful
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: fix, size/XS

#173 Add more info output to /delremind
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/RemindCommandGroup.cs
  src/Messages.Designer.cs
Labels: size/S, type: change

#171 Notify user when a command execution error occurs
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Extensions/LoggerExtensions.cs
  src/Messages.Designer.cs
Labels: type: feature, size/S

#172 Handle guild data load errors better
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Data/GuildData.cs
  src/Messages.Designer.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildUnloadedResponder.cs
  src/Services/GuildDataService.cs
Labels: type: fix, size/M

#174 Limit string argument length to avoid "embed description too long" errors
  src/Commands/BanCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
Labels: type: fix, size/S

#175 Disable text commands
  src/Octobot.cs
Labels: type: fix, size/XS
