Repository TeamOctolings/Octobot, pull requests merged in 2023-08, with the labels that each got.

#75 Add logging to file
  Boyfriend.csproj
  src/Boyfriend.cs
Labels: type: enhancement, size/XS

#76 Add a new .editorconfig and reformat code
  .editorconfig
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Boyfriend.cs
  src/ColorsList.cs
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/Events/LoggingPreparationErrorEvent.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Data/GuildData.cs
  src/Data/GuildSettings.cs
  src/Data/MemberData.cs
  src/Data/Options/BoolOption.cs
  src/Data/Options/IOption.cs
  src/Data/Options/LanguageOption.cs
  src/Data/Options/Option.cs
  src/Data/Options/SnowflakeOption.cs
  src/Data/Options/TimeSpanOption.cs
  src/Data/Reminder.cs
  src/Data/ScheduledEventData.cs
  src/Extensions.cs
  src/InteractionResponders.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Responders/GuildMemberRolesUpdatedResponder.cs
  src/Responders/MessageDeletedResponder.cs
  src/Responders/MessageEditedResponder.cs
  src/Responders/MessageReceivedResponder.cs
  src/Responders/ScheduledEventCancelledResponder.cs
  src/Services/GuildDataService.cs
  src/Services/GuildUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: security & quality, size/XXL

#78 Fix roles not returning on rejoin if welcome messages were disabled
  src/Responders/GuildMemberJoinedResponder.cs
Labels: type: bugfix, size/XS

#79 Log guild setting changes to PrivateFeedbackChannel
  src/Commands/SettingsCommandGroup.cs
Labels: type: bugfix, size/S

#77 Backfill member data when a guild is loaded or a new member joins it
  .editorconfig
  src/Boyfriend.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Data/GuildData.cs
  src/Data/MemberData.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Services/GuildDataService.cs
Labels: type: bugfix, size/S

#80 Split GuildUpdateService into separate services
  src/Boyfriend.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/Events/LoggingPreparationErrorEvent.cs
  src/Commands/MuteCommandGroup.cs
  src/Extensions.cs
  src/Services/GuildUpdateService.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Update/ScheduledEventUpdateService.cs
  src/Services/Update/SongUpdateService.cs
Labels: type: bugfix, type: enhancement, type: security & quality, size/XL

#82 Add /listremind and /delremind
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/RemindCommandGroup.cs
  src/Messages.Designer.cs
Labels: type: enhancement, size/M

#81 Scheduled event update bugfixes
  src/Data/ScheduledEventData.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: bugfix, size/XS

#83 Fix a crash in scheduled event early notification
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: bugfix, size/XS, priority: high

#84 EventEarlyNotification timestamp bugfix and other changes
  locale/Messages.tt-ru.resx
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: bugfix, type: docs, size/S

#88 Add failed embed for /listremind
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/RemindCommandGroup.cs
  src/Messages.Designer.cs
Labels: size/S

#89 Fix various issues with ScheduledEventUpdateService
  src/Data/ScheduledEventData.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/ScheduledEventCancelledResponder.cs
  src/Responders/ScheduledEventCreatedResponder.cs
  src/Responders/ScheduledEventUpdatedResponder.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: bugfix, size/L

#90 Add automatic deployment
  .editorconfig
  .github/workflows/build-pr.yml
  .github/workflows/build-push.yml
  .github/workflows/resharper.yml
Labels: type: enhancement, size/M

#92 Add a JSON deserialization constructor for ScheduledEventData
  src/Data/ScheduledEventData.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/ScheduledEventCreatedResponder.cs
Labels: type: bugfix, size/S

#93 Change organization name references from TeamOctolings to LabsDevelopment
  .github/CODEOWNERS
  Boyfriend.csproj
  docs/CONTRIBUTING.md
  docs/README.md
  src/Commands/AboutCommandGroup.cs
Labels: type: docs, size/S

#94 Rename settings commands
  src/Commands/SettingsCommandGroup.cs
Labels: size/XS

#98 Add autocomplete for /editsettings setting keys
  src/Commands/SettingsCommandGroup.cs
  src/Data/Options/AllOptionsEnum.cs
Labels: type: bugfix, type: enhancement, size/S

#99 Add periodic guild data saving (every 5 minutes)
  src/Boyfriend.cs
  src/Services/BackgroundGuildDataSaverService.cs
  src/Services/GuildDataService.cs
Labels: type: enhancement, size/S

#100 Fix JSON corruption when saving
  CodeAnalysis/BannedSymbols.txt
  src/Services/GuildDataService.cs
Labels: type: bugfix, size/XS, priority: high
