Repository TeamOctolings/Octobot, pull requests merged in 2023-12, with the labels that each got.

#206 Add StringBuilder & Markdown extensions
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Extensions/MarkdownExtensions.cs
  src/Extensions/StringBuilderExtensions.cs
Labels: size/M, type: refactor/style

#208 Fix inspection warnings
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Data/MemberData.cs
  src/Services/GuildDataService.cs
  src/Services/Update/SongUpdateService.cs
Labels: size/S, type: refactor/style

#210 Rewrite music list
  src/Services/Update/SongUpdateService.cs
Labels: size/S, area: song list, type: change

#211 Add application icon
  Octobot.csproj
  docs/octobot.ico
Labels: type: feature, size/XS

#203 Add link to original message for activated reminders and /listremind
  src/Commands/RemindCommandGroup.cs
  src/Data/Reminder.cs
  src/Services/Update/MemberUpdateService.cs
Labels: type: feature, size/S

#213 Recommend to install .NET 8 in README.md
  docs/README.md
Labels: type: fix, area: docs, size/XS

#214 Bump Remora.Commands to fix issue with optional slash command args
  Octobot.csproj
Labels: type: fix, size/XS, priority: high

#216 Disable "Convert to Primary Constructor" warning
  .editorconfig
Labels: size/XS, type: change

#219 FeedbackServiceExtensions: Add options support
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Extensions/FeedbackServiceExtensions.cs
Labels: type: feature, size/S

#217 Add ChannelApiExtensions
  src/Commands/BanCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Extensions/ChannelApiExtensions.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Responders/MessageDeletedResponder.cs
  src/Responders/MessageEditedResponder.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Update/ScheduledEventUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: feature, size/M

#218 /about: Add repository link button
  src/Commands/AboutCommandGroup.cs
Labels: type: feature, size/XS

#202 Don't log edited messages by bots
  src/Responders/MessageEditedResponder.cs
Labels: size/S, type: breaking change

#221 Add issue button w/ some button updates
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/AboutCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Messages.Designer.cs
  src/Octobot.cs
  src/Responders/GuildLoadedResponder.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: feature, size/S

#222 README: Add invite button
  docs/README.md
Labels: area: docs, size/XS, type: change

#226 /about: Show link to GitHub profile if Discord member wasn't found
  src/Commands/AboutCommandGroup.cs
  src/Extensions/MarkdownExtensions.cs
Labels: type: feature, size/XS

#229 /about: Casually remember about Markdown.Hyperlink
  src/Commands/AboutCommandGroup.cs
  src/Extensions/MarkdownExtensions.cs
Labels: size/XS, type: change

#238 Use collection expressions in more places
  src/Commands/AboutCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Update/SongUpdateService.cs
Labels: size/S, type: refactor/style

#230 /about: Show Discord bot username instead of hardcoded one
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/AboutCommandGroup.cs
Labels: size/XS, type: change

#236 Remove "extends IHostedService" from classes where it's not required
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Octobot.cs
  src/Responders/GuildLoadedResponder.cs
  src/Services/GuildDataService.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Update/ScheduledEventUpdateService.cs
  src/Services/Utility.cs
Labels: size/S, type: refactor/style

#239 Merge BackgroundGuildDataSaverService into GuildDataService
  src/Octobot.cs
  src/Services/BackgroundGuildDataSaverService.cs
  src/Services/GuildDataService.cs
Labels: size/S, type: refactor/style

#240 Use AddFromAssembly for responders and command groups
  src/Octobot.cs
Labels: size/S, type: refactor/style

#235 Add profiler base
  src/Octobot.cs
  src/Services/Profiler/Profiler.cs
  src/Services/Profiler/ProfilerEvent.cs
  src/Services/Profiler/ProfilerFactory.cs
Labels: type: feature, size/M

#242 /userinfo: Show if the user was kicked w/ updates
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Data/MemberData.cs
  src/Messages.Designer.cs
  src/Responders/GuildMemberJoinedResponder.cs
Labels: type: feature, size/S

#243 Ban usages of Thread#Sleep
  CodeAnalysis/BannedSymbols.txt
Labels: size/XS, area: build/ci, type: change

#245 Fix newline in LogResult
  src/Extensions/LoggerExtensions.cs
Labels: type: fix, size/XS

#223 Use custom TimeSpanParser
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/BanCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Data/Options/TimeSpanOption.cs
  src/Messages.Designer.cs
  src/Parsers/TimeSpanParser.cs
Labels: type: fix, size/M
