Repository TeamOctolings/Octobot, pull requests merged in 2023-09, with the labels that each got.

#102 Allow better customisation of autodeploy through secrets and variables
  .github/workflows/build-push.yml
Labels: type: security & quality, size/S

#106 Force enumeration of global collections before using them
  src/Commands/RemindCommandGroup.cs
  src/Services/GuildDataService.cs
  src/Services/Update/MemberUpdateService.cs
Labels: type: bugfix, size/XS, priority: high

#107 Add MORE music to the bot
  src/Services/Update/SongUpdateService.cs
Labels: size/XS

#108 Change logo CDN
  docs/README.md
  src/Commands/AboutCommandGroup.cs
  src/Services/Update/SongUpdateService.cs
Labels: size/XS

#109 Add mute role support & fix /unmute
  src/Commands/MuteCommandGroup.cs
  src/Data/MemberData.cs
  src/Responders/GuildMemberRolesUpdatedResponder.cs
  src/Services/Update/MemberUpdateService.cs
Labels: type: bugfix, type: enhancement, size/M

#110 Move all GuildData to one folder
  src/Services/GuildDataService.cs
Labels: size/S

#113 Disable the logging of `SaveAsync` due to spam in the logs
  src/Services/GuildDataService.cs
Labels: type: security & quality, size/XS

#111 Add /resetsettings
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/SettingsCommandGroup.cs
  src/Data/Options/IOption.cs
  src/Data/Options/Option.cs
  src/Messages.Designer.cs
Labels: type: enhancement, size/M

#114 Set MemberData.BannedUntil to null in /unban
  src/Commands/BanCommandGroup.cs
Labels: type: security & quality, size/XS

#115 Fix UnknownMember warning flood
  src/Services/Update/MemberUpdateService.cs
Labels: type: bugfix, size/S

#118 Skip refreshing roles if the member is role-muted
  src/Services/GuildDataService.cs
Labels: type: bugfix, size/XS

#119 Fix auto-unban and auto-unmute always triggering
  src/Services/Update/MemberUpdateService.cs
Labels: type: bugfix, size/XS, priority: high

#121 Fix mute role returning when rejoining server
  src/Responders/GuildMemberJoinedResponder.cs
Labels: type: bugfix, size/S

#122 Add /showinfo
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Boyfriend.cs
  src/Commands/ToolsCommandGroup.cs
  src/Extensions.cs
  src/Messages.Designer.cs
Labels: type: enhancement, size/L

#125 Add some Splatoon™ songs that I liked
  src/Services/Update/SongUpdateService.cs
Labels: size/XS, type: song list

#123 Redesign embeds
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Extensions.cs
  src/Messages.Designer.cs
  src/Responders/MessageDeletedResponder.cs
  src/Responders/MessageEditedResponder.cs
Labels: type: enhancement, size/XXL

#127 Add /random
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/ToolsCommandGroup.cs
  src/Messages.Designer.cs
Labels: type: enhancement, size/S

#129 Synchronize scheduled events on sch. events tick
  src/Responders/GuildLoadedResponder.cs
  src/Responders/ScheduledEventCreatedResponder.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: bugfix, size/S

#130 Synchronize roles only on member data updates
  src/Responders/GuildMemberRolesUpdatedResponder.cs
  src/Services/GuildDataService.cs
  src/Services/Update/MemberUpdateService.cs
Labels: type: security & quality, size/S

#131 Synchronize events only on sch. event updates
  src/Responders/GuildLoadedResponder.cs
  src/Responders/ScheduledEventUpdatedResponder.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: security & quality, size/S

#132 Run scheduled event updates synchronously to avoid a rate limit error
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: bugfix, size/XS

#133 Don't forget to remove scheduled event data when notification channel is not set
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: bugfix, size/XS

#134 Use Snowflake#Empty extension method instead of '== 0' checks
  src/Commands/MuteCommandGroup.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: security & quality, size/XS
