Repository TeamOctolings/Octobot, pull requests merged in 2023-01, with the labels that each got.

#13 Refactor guild data storage
  .github/dependabot.yml
  .github/workflows/resharper.yml
  Boyfriend/Boyfriend.cs
  Boyfriend/CommandProcessor.cs
  Boyfriend/Commands/BanCommand.cs
  Boyfriend/Commands/ClearCommand.cs
  Boyfriend/Commands/HelpCommand.cs
  Boyfriend/Commands/KickCommand.cs
  Boyfriend/Commands/MuteCommand.cs
  Boyfriend/Commands/PingCommand.cs
  Boyfriend/Commands/RemindCommand.cs
  Boyfriend/Commands/SettingsCommand.cs
  Boyfriend/Commands/UnbanCommand.cs
  Boyfriend/Commands/UnmuteCommand.cs
  Boyfriend/Data/GuildData.cs
  Boyfriend/Data/MemberData.cs
  Boyfriend/Data/Reminder.cs
  Boyfriend/EventHandler.cs
  Boyfriend/Messages.Designer.cs
  Boyfriend/Messages.resx
  Boyfriend/Messages.ru.resx
  Boyfriend/Messages.tt-ru.resx
  Boyfriend/ReplyEmojis.cs
  Boyfriend/Utils.cs
Labels: type: enhancement, type: security & quality

#16 Fix GitHub workflow status badge
  README.md
Labels: type: docs

#23 Fix removing everyone role while muting
  Commands/MuteCommand.cs
Labels: type: bugfix
