Repository TeamOctolings/Octobot, pull requests merged in 2023-07, with the labels that each got.

#41 Switch to Remora.Discord
  .editorconfig
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/README.md
  .github/workflows/codeql.yml
  .github/workflows/resharper.yml
  .gitignore
  Boyfriend.cs
  Boyfriend.csproj
  ColorsList.cs
  CommandProcessor.cs
  Commands/AboutCommandGroup.cs
  Commands/BanCommand.cs
  Commands/BanCommandGroup.cs
  Commands/ClearCommand.cs
  Commands/ClearCommandGroup.cs
  Commands/ErrorLoggingEvents.cs
  Commands/HelpCommand.cs
  Commands/ICommand.cs
  Commands/KickCommand.cs
  Commands/KickCommandGroup.cs
  Commands/MuteCommand.cs
  Commands/MuteCommandGroup.cs
  Commands/PingCommand.cs
  Commands/PingCommandGroup.cs
  Commands/RemindCommand.cs
  Commands/RemindCommandGroup.cs
  Commands/SettingsCommand.cs
  Commands/SettingsCommandGroup.cs
  Commands/UnbanCommand.cs
  Commands/UnmuteCommand.cs
  Data/GuildConfiguration.cs
  Data/GuildData.cs
  Data/MemberData.cs
  Data/Reminder.cs
  Data/ScheduledEventData.cs
  EventHandler.cs
  EventResponders.cs
  Extensions.cs
  InteractionResponders.cs
  Messages.Designer.cs
  Messages.resx
  Messages.ru.resx
  Messages.tt-ru.resx
  ReplyEmojis.cs
  Services/GuildDataService.cs
  Services/GuildUpdateService.cs
  Services/UtilityService.cs
  Utils.cs
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/README.md
Labels: type: enhancement, type: security & quality, type: dependencies

#46 Fix some issues with slash commands & add missing docs
  Boyfriend.csproj
  Commands/KickCommandGroup.cs
  Commands/MuteCommandGroup.cs
  Commands/RemindCommandGroup.cs
  Commands/SettingsCommandGroup.cs
  Extensions.cs
  Messages.Designer.cs
  Messages.resx
  Messages.ru.resx
  Messages.tt-ru.resx
  docs/README.md
Labels: type: bugfix, type: docs, type: security & quality

#47 Tidy up project structure, fix bug with edit logging
  .github/CODEOWNERS
  Boyfriend.csproj
  docs/README.md
  locale/Messages.Designer.cs
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Boyfriend.cs
  src/ColorsList.cs
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/ErrorLoggingEvents.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Data/GuildConfiguration.cs
  src/Data/GuildData.cs
  src/Data/MemberData.cs
  src/Data/Reminder.cs
  src/Data/ScheduledEventData.cs
  src/EventResponders.cs
  src/Extensions.cs
  src/InteractionResponders.cs
  src/Services/GuildDataService.cs
  src/Services/GuildUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: bugfix, type: docs, type: security & quality

#48 The Milestone Commit
  .github/workflows/resharper.yml
  Boyfriend.csproj
  docs/README.md
  docs/assets/boyfriend.png
  src/Boyfriend.cs
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/ErrorLoggingEvents.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Data/GuildConfiguration.cs
  src/Data/GuildData.cs
  src/Data/GuildSettings.cs
  src/Data/MemberData.cs
  src/Data/Options/BoolOption.cs
  src/Data/Options/IOption.cs
  src/Data/Options/LanguageOption.cs
  src/Data/Options/Option.cs
  src/Data/Options/SnowflakeOption.cs
  src/Data/Options/TimeSpanOption.cs
  src/Data/Reminder.cs
  src/EventResponders.cs
  src/Extensions.cs
  src/InteractionResponders.cs
  src/Messages.Designer.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Responders/GuildMemberRolesUpdatedResponder.cs
  src/Responders/MessageDeletedResponder.cs
  src/Responders/MessageEditedResponder.cs
  src/Responders/MessageReceivedResponder.cs
  src/Responders/ScheduledEventCancelledResponder.cs
  src/Services/GuildDataService.cs
  src/Services/GuildUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: docs, type: security & quality, size/XXL

#49 Do not allow certain commands to be used in DMs
  src/Commands/AboutCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
Labels: type: bugfix, size/S

#52 Increase thresholds for size labels
  .github/labels.yml
Labels: type: enhancement, size/S

#51 Split error logging events into separate files
  src/Boyfriend.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/Events/LoggingPreparationErrorEvent.cs
Labels: type: security & quality, size/M

#50 Reduce method complexity in /ban, /unban and some other commands
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Extensions.cs
  src/Services/UtilityService.cs
Labels: type: security & quality, size/L

#55 Reduce method complexity of UtilityService#CheckInteractionsAsync
  src/Services/UtilityService.cs
Labels: type: security & quality, size/S

#54 General fixes
  .github/workflows/resharper.yml
  src/Commands/BanCommandGroup.cs
  src/Data/Options/LanguageOption.cs
  src/Responders/MessageDeletedResponder.cs
  src/Services/UtilityService.cs
Labels: type: bugfix, type: security & quality, size/S

#56 Reduce method complexity of /clear
  src/Commands/ClearCommandGroup.cs
Labels: type: security & quality, size/S

#57 Remove "code quality" badge
  docs/README.md
Labels: type: docs, size/XS

#59 Do not assign Octol1ttle for Dependabot PRs
  .github/dependabot.yml
Labels: type: dependencies, size/XS

#60 Force maximum Cognitive Complexity via InspectCode
  .github/workflows/resharper.yml
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/InteractionResponders.cs
  src/Services/GuildUpdateService.cs
Labels: type: security & quality, size/L

#63 Remove non-numbers from SnowflakeOption inputs
  src/Data/Options/SnowflakeOption.cs
Labels: type: bugfix, size/XS

#64 Add Color and Public parameters to LogActionAsync
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Services/UtilityService.cs
Labels: type: enhancement, size/S

#70 Add code analysis to prohibit using bad methods and properties
  Boyfriend.csproj
  CodeAnalysis/BannedSymbols.txt
Labels: type: security & quality, size/S

#65 Improved /settingslist + fixed /settings pt.1
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/SettingsCommandGroup.cs
  src/Data/Options/BoolOption.cs
  src/Messages.Designer.cs
Labels: type: bugfix, type: enhancement, size/S

#71 Replace "ToLower" with "ToLowerInvariant" to fix a missed warning
  src/Data/Options/BoolOption.cs
Labels: type: security & quality, size/XS

#72 Resolving issues on #65
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/SettingsCommandGroup.cs
Labels: type: bugfix, type: security & quality, size/S

#73 Do not wrap result errors when returning them
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Data/Options/BoolOption.cs
  src/Data/Options/LanguageOption.cs
  src/Data/Options/SnowflakeOption.cs
  src/Data/Options/TimeSpanOption.cs
  src/InteractionResponders.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Responders/MessageEditedResponder.cs
  src/Services/GuildUpdateService.cs
  src/Services/UtilityService.cs
Labels: type: security & quality, size/S

#74 Add soundtracks from different games
  src/Services/GuildUpdateService.cs
Labels: size/XS
