Repository TeamOctolings/Octobot, pull requests merged in 2024-07, with the labels that each got.

#323 Bump InspectCode from 1.11.10 to 1.11.12
  .github/workflows/build-pr.yml
Labels: type: fix, size/XS, priority: high, area: build/ci

#321 Redesign reminder-related commands
  TeamOctolings.Octobot/Commands/RemindCommandGroup.cs
  TeamOctolings.Octobot/Extensions/MarkdownExtensions.cs
  TeamOctolings.Octobot/Services/Update/MemberUpdateService.cs
Labels: size/S, type: change

#326 Show an error when entering the same value from the settings
  TeamOctolings.Octobot/Commands/SettingsCommandGroup.cs
  TeamOctolings.Octobot/Data/Options/BoolOption.cs
  TeamOctolings.Octobot/Data/Options/GuildOption.cs
  TeamOctolings.Octobot/Data/Options/IGuildOption.cs
  TeamOctolings.Octobot/Data/Options/LanguageOption.cs
  TeamOctolings.Octobot/Data/Options/TimeSpanOption.cs
  TeamOctolings.Octobot/Messages.Designer.cs
  TeamOctolings.Octobot/Messages.resx
  TeamOctolings.Octobot/Messages.ru.resx
Labels: type: fix, size/S

#327 Don't log stack traces for cancelled operations
  TeamOctolings.Octobot/Extensions/LoggerExtensions.cs
  TeamOctolings.Octobot/Extensions/ResultExtensions.cs
Labels: type: fix, size/XS
