Repository TeamOctolings/Octobot, pull requests merged in 2024-03, with the labels that each got.

#264 Add /8ball command
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/ToolsCommandGroup.cs
  src/Messages.Designer.cs
Labels: size/L

#267 Add time format example to the description of commands that use TimeSpan.
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/BanCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Messages.Designer.cs
Labels: size/S, type: change

#269 Add WelcomeMessagesChannel setting
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/SettingsCommandGroup.cs
  src/Data/GuildSettings.cs
  src/Data/Options/AllOptionsEnum.cs
  src/Messages.Designer.cs
  src/Responders/GuildMemberJoinedResponder.cs
Labels: type: feature, size/S

#273 Remove unused IDiscordRestChannelAPI in ToolsCommandGroup
  src/Commands/ToolsCommandGroup.cs
Labels: size/XS, type: refactor/style

#271 Fix auto-unban log spam
  src/Services/Update/MemberUpdateService.cs
Labels: type: fix, size/XS

#270 Rename locale Sound to Loaded for clarity
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Messages.Designer.cs
  src/Responders/GuildLoadedResponder.cs
Labels: size/S, type: change, area: i18n

#268 Add GitInfo NuGet package
  Octobot.csproj
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/BuildInfo.cs
  src/Commands/AboutCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Messages.Designer.cs
  src/Octobot.cs
  src/Responders/GuildLoadedResponder.cs
Labels: type: feature, size/S

#234 Add "Member left" message
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/BanCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Data/GuildSettings.cs
  src/Data/Options/AllOptionsEnum.cs
  src/Messages.Designer.cs
  src/Responders/GuildMemberLeftResponder.cs
Labels: type: feature, size/M

#276 Fix /ping not showing correct locale
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/PingCommandGroup.cs
  src/Messages.Designer.cs
  src/Responders/GuildLoadedResponder.cs
Labels: type: fix, size/S, type: change

#275 Disable issue report button if dirty version detected
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/BuildInfo.cs
  src/Commands/AboutCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Messages.Designer.cs
  src/Responders/GuildLoadedResponder.cs
Labels: type: feature, size/S

#279 Change position of "Jump to ..." action for better consistency
  src/Responders/MessageDeletedResponder.cs
  src/Responders/MessageEditedResponder.cs
Labels: size/XS, type: change

#282 Log result failures with stack traces
  src/Attributes/StaticCallersOnlyAttribute.cs
  src/Commands/AboutCommandGroup.cs
  src/Commands/BanCommandGroup.cs
  src/Commands/ClearCommandGroup.cs
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/PingCommandGroup.cs
  src/Commands/RemindCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Extensions/ChannelApiExtensions.cs
  src/Extensions/FeedbackServiceExtensions.cs
  src/Extensions/ResultExtensions.cs
  src/Octobot.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Responders/GuildMemberLeftResponder.cs
  src/Responders/MessageDeletedResponder.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: type: feature, size/L

#283 Use Result.Success property instead of Result.FromSuccess()
  src/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  src/Commands/Events/LoggingPreparationErrorEvent.cs
  src/Commands/MuteCommandGroup.cs
  src/Data/Options/BoolOption.cs
  src/Data/Options/Option.cs
  src/Data/Options/SnowflakeOption.cs
  src/Data/Options/TimeSpanOption.cs
  src/Extensions/CollectionExtensions.cs
  src/Extensions/GuildScheduledEventExtensions.cs
  src/Responders/GuildLoadedResponder.cs
  src/Responders/GuildMemberJoinedResponder.cs
  src/Responders/GuildMemberLeftResponder.cs
  src/Responders/GuildUnloadedResponder.cs
  src/Responders/MessageDeletedResponder.cs
  src/Responders/MessageEditedResponder.cs
  src/Responders/MessageReceivedResponder.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Update/ScheduledEventUpdateService.cs
Labels: size/M, type: refactor/style

#285 Pre-Wiki Update
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/BuildInfo.cs
  src/Commands/AboutCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Commands/ToolsCommandGroup.cs
  src/Messages.Designer.cs
Labels: type: feature, size/S, type: change

#286 Don't use BannedUntil in MemberData.<init>
  src/Data/MemberData.cs
Labels: size/XS, type: refactor/style

#287 fix: do not use RepositoryUrl from GitInfo
  src/BuildInfo.cs
Labels: type: fix, size/XS, type: refactor/style

#289 Do not use ResultError#IsUserOrEnvironmentError
  src/Extensions/LoggerExtensions.cs
Labels: type: fix, size/XS

#288 Split message clear log when cleared messages are too long
  src/Commands/ClearCommandGroup.cs
Labels: type: fix, size/S

#290 Add 'ModeratorRole' guild setting
  locale/Messages.resx
  locale/Messages.ru.resx
  locale/Messages.tt-ru.resx
  src/Commands/BanCommandGroup.cs
  src/Commands/KickCommandGroup.cs
  src/Commands/MuteCommandGroup.cs
  src/Commands/SettingsCommandGroup.cs
  src/Data/GuildSettings.cs
  src/Data/Options/AllOptionsEnum.cs
  src/Octobot.cs
  src/Services/AccessControlService.cs
  src/Services/Update/MemberUpdateService.cs
  src/Services/Utility.cs
Labels: type: feature, size/L

#291 Rename currentMember to botMember
  src/Services/AccessControlService.cs
Labels: size/XS, type: refactor/style

#293 Fix "No operation context has been set for this scope." crash on startup
  src/Services/AccessControlService.cs
Labels: type: fix, size/S, priority: high
