Repository TeamOctolings/Octobot, pull requests merged in 2024-06, with the labels that each got.

#316 README: Refer to the Octobot's Wiki in Building Octobot
  docs/README.md
Labels: area: docs, size/XS, type: change

#317 Handle audit log entries for message deletion being empty
  TeamOctolings.Octobot/Responders/MessageDeletedResponder.cs
Labels: type: fix, size/XS

#319 Always default cancellation tokens
  TeamOctolings.Octobot/Commands/InfoCommandGroup.cs
  TeamOctolings.Octobot/Commands/MuteCommandGroup.cs
  TeamOctolings.Octobot/Commands/RemindCommandGroup.cs
  TeamOctolings.Octobot/Commands/ToolsCommandGroup.cs
  TeamOctolings.Octobot/Responders/GuildLoadedResponder.cs
  TeamOctolings.Octobot/Responders/GuildMemberJoinedResponder.cs
  TeamOctolings.Octobot/Services/GuildDataService.cs
  TeamOctolings.Octobot/Services/Update/MemberUpdateService.cs
  TeamOctolings.Octobot/Services/Update/ScheduledEventUpdateService.cs
  TeamOctolings.Octobot/Utility.cs
Labels: size/S, type: refactor/style
