Repository TeamOctolings/Octobot, pull requests merged in 2024-05, with the labels that each got.

#304 Dependabot: ignore patch updates
  .github/dependabot.yml
Labels: size/XS, area: build/ci, type: change

#305 Enable result stacktraces in release mode
  src/Extensions/ResultExtensions.cs
Labels: size/XS, type: change

#308 Separate /*info commands from ToolsCommandGroup
  TeamOctolings.Octobot/Commands/InfoCommandGroup.cs
  TeamOctolings.Octobot/Commands/ToolsCommandGroup.cs
Labels: size/L, type: refactor/style

#309 Seal implicitly used classes
  TeamOctolings.Octobot/Commands/AboutCommandGroup.cs
  TeamOctolings.Octobot/Commands/BanCommandGroup.cs
  TeamOctolings.Octobot/Commands/ClearCommandGroup.cs
  TeamOctolings.Octobot/Commands/Events/ErrorLoggingPostExecutionEvent.cs
  TeamOctolings.Octobot/Commands/Events/LoggingPreparationErrorEvent.cs
  TeamOctolings.Octobot/Commands/InfoCommandGroup.cs
  TeamOctolings.Octobot/Commands/KickCommandGroup.cs
  TeamOctolings.Octobot/Commands/MuteCommandGroup.cs
  TeamOctolings.Octobot/Commands/PingCommandGroup.cs
  TeamOctolings.Octobot/Commands/RemindCommandGroup.cs
  TeamOctolings.Octobot/Commands/SettingsCommandGroup.cs
  TeamOctolings.Octobot/Commands/ToolsCommandGroup.cs
  TeamOctolings.Octobot/Responders/GuildLoadedResponder.cs
  TeamOctolings.Octobot/Responders/GuildMemberJoinedResponder.cs
  TeamOctolings.Octobot/Responders/GuildMemberLeftResponder.cs
  TeamOctolings.Octobot/Responders/GuildUnloadedResponder.cs
  TeamOctolings.Octobot/Responders/MessageDeletedResponder.cs
  TeamOctolings.Octobot/Responders/MessageEditedResponder.cs
  TeamOctolings.Octobot/Responders/MessageReceivedResponder.cs
Labels: size/S, type: refactor/style

#312 Use MemberData roles when checking permissions & interactions
  TeamOctolings.Octobot/Services/AccessControlService.cs
Labels: type: fix, size/S, type: breaking change

#313 Upgrade NuGet dependencies
  TeamOctolings.Octobot/Extensions/ChannelApiExtensions.cs
  TeamOctolings.Octobot/TeamOctolings.Octobot.csproj
Labels: size/XS, area: build/ci, type: change

#315 Add description to /clear's author to clarify its functionality
  TeamOctolings.Octobot/Commands/ClearCommandGroup.cs
Labels: type: feature, size/XS
